database:
  tables:
    tag_and_object:
      index:
        path: /tmp/dream/benchmark/tables/tag_and_object/index.idx
      data_pool:
        Fixed:
          path: /tmp/dream/benchmark/tables/tag_and_object/data.dat
          container_size: 32
    object_and_tag:
      index:
        path: /tmp/dream/benchmark/tables/object_and_tag/index.idx
      data_pool:
        Fixed:
          path: /tmp/dream/benchmark/tables/object_and_tag/data.dat
          container_size: 32
    id_to_source:
      index:
        path: /tmp/dream/benchmark/tables/id_to_source/index.idx
      data_pool:
        Variable:
          directory: /tmp/dream/benchmark/tables/id_to_source/data
          max_element_size: 65536
    tag_to_objects_count:
      index:
        path: /tmp/dream/benchmark/tables/tag_to_objects_count/index.idx
      data_pool:
        Fixed:
          path: /tmp/dream/benchmark/tables/tag_to_objects_count/data.dat
          container_size: 20
    object_to_tags_count:
      index:
        path: /tmp/dream/benchmark/tables/object_to_tags_count/index.idx
      data_pool:
        Fixed:
          path: /tmp/dream/benchmark/tables/object_to_tags_count/data.dat
          container_size: 20
  log:
    path: /tmp/dream/benchmark/log.dat
